### PR TITLE
MiuiCamera: Bypass tissot_sprout check

### PR DESCRIPTION
**Pull request by danielstuart14**
The previous patch proposed by me wasn't working because  of some weird signature issue.

I tested this one using the stock 8.1 and it worked fine (the previous one wasn't working, indeed).
Still, I encourage you to test it with a custom rom, but it should work.

I explained what I did in the commit message.

### CODE REVIEW

**Comment by joeyhuab** [comment]
I'll test this out :) Thank you so much for checking the previous patch. It indeed installed but wasn't able to open up.

**Comment by joeyhuab** [comment]
Thanks for the patch! Will include in the next release to the repo.

**Comment by danielstuart14** [comment]
your welcome! Now I can switch to a custom rom hehe
Thank you for the module!

**Comment by joeyhuab** [comment]
Not a problem! Thanks for your help as well. Changes should be in the repo already.

**Pull request merged**
